x-transition:enter="transition-all transform ease-out duration-300"
x-transition:enter-start="opacity-0 scale-95 -translate-y-[30px]"
x-transition:enter-end="opacity-100 scale-100 translate-y-0"
x-transition:leave="transition-all transform ease-in duration-200"
x-transition:leave-start="opacity-100 scale-100 translate-y-0"
x-transition:leave-end="opacity-0 scale-95 -translate-y-[30px]"